# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       pcre

# >> macros
# << macros
%define keepstatic 1

Summary:    Perl-compatible regular expression library
Version:    8.31
Release:    2
Group:      System/Libraries
License:    BSD
URL:        http://www.pcre.org/
Source0:    ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/%{name}-%{version}.tar.bz2
Source100:  pcre.yaml
# Fix unused memory usage on zero-repeat assertion condition.
# CVE-2014-8964, in upstream after 8.36
Patch0: pcre-8.33-Fix-zero-repeat-assertion-condition-bug.patch
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  autoconf
BuildRequires:  automake
BuildRequires:  libtool

%description
Perl-compatible regular expression library.
PCRE has its own native API, but a set of "wrapper" functions that are based on
the POSIX API are also supplied in the library libpcreposix. Note that this
just provides a POSIX calling interface to PCRE: the regular expressions
themselves still follow Perl syntax and semantics. The header file
for the POSIX-style functions is called pcreposix.h.


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Development files (Headers, libraries for dynamic linking, etc) for %{name}.

%package static
Summary:    Static libraries files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description static
Static development files for %{name}.


%prep
%setup -q -n %{name}-%{version}
# >> setup
%patch0 -p1 -b .zero_repeat_assertion
# << setup

%build
# >> build pre
libtoolize --copy --force && autoreconf
# One contributor's name is non-UTF-8
for F in ChangeLog; do
iconv -f latin1 -t utf8 "$F" >"${F}.utf8"
touch --reference "$F" "${F}.utf8"
mv "${F}.utf8" "$F"
done
# << build pre

%configure  \
%ifnarch aarch64
    --enable-jit \
%endif
    --enable-utf \
    --enable-unicode-properties \
    --enable-pcre8 \
    --enable-pcre16

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%check
# >> check
make check
# << check

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%{_libdir}/*.so.*
%{_bindir}/pcregrep
%{_bindir}/pcretest
%doc %{_mandir}/*/*.gz
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_libdir}/*.so
%{_libdir}/pkgconfig/*
%{_includedir}/*.h
%{_bindir}/pcre-config
%doc %{_docdir}/pcre
# << files devel

%files static
%defattr(-,root,root,-)
# >> files static
%{_libdir}/*.a
# << files static
